name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: githubactionintegrationyudith
          cx_tenant: cx_pm_ast_ori_james_brotsos_tenant
          base_uri: https://ast.checkmarx.net
          #cx_client_id: ${{ secrets.CLIENT_ID }}
          #cx_client_secret: ${{ secrets.SECRET }}
          #additional_params: --apikey ${{ secrets.apisecret }}
          additional_params: --apikey ${{ secrets.apisecret }} --debug --file-filter '!*' --file-include'serv'
          #PresetName: 'checkmarx default'
          #additional_params: --report-format sarif
    
